--- 
abstract: Automatic Pagination using AutoPagerize
author: 
  - Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Mechanize-AutoPager
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::AutoPagerize: 0
  JSON: 2.09
  WWW::Mechanize: 0
  WWW::Mechanize::DecodedContent: 0
  perl: 5.8.1
version: 0.02
